# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15422282388234e3a3bba323289263b30c7f6748dd1240f1a889a634e114bd7f166293c26882b762044c037e10cdb332be2b2a88ebfb1f3c59fd1a5be6e99f41

test:
  secret_key_base: 47dbcc5d4c65394a3e3b032c4b2d3c2890ada2441a0fd3a9d25c8cd62bc5fe3fdb9585c55c2a68cb2473c419b9178103c8cbb21475cf87925f38247bec44b4a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
