# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff272d82ce0e3d77bb99c1d82ef7a6a4762c8193c18d9550c6531e78955fb90f420c2295db1b27a2205b58e0c9879c8b3181009c8f1c817b47874fa1fc98d966

test:
  secret_key_base: cba1b85badb3518e0fa69201d76df497e874c2ff2f1c8ecb258a0846e29ac9e2ebc6b47869013c2acc0fd63716f16bc4f6dbd2bb52d9640aa24cf5401917b0dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
